### ISSUE TITLE
Feature: Include sample pages to get users started

### ISSUE THREAD

**Issue by edwardhorsford** [tombye/express_prototype#6]
Starter pages:

Start pages (old / new)
Guide
Quick answer
GOV.UK Homepage

---
I had a go doing this myself, but after grabbing css from frontend still didn't seem to get everything needed.

**Comment by tombye** [comment]
I'd say non-library GOVUK code shouldn't be part of the default app as a general rule.

If you want to contribute experience of how you've gone about scraping code from www.gov.uk (or rather the project repos for it), it should be in the form of instructions rather than the code. This would mean the instructions stay relevant when the code changes (which is happening a lot at the moment).
